source 'https://github.com/CocoaPods/Specs.git'
platform :ios, '10.0'
use_frameworks!

target 'FeedTrue' do
pod 'Alamofire', '~> 4.7'
pod 'AlamofireObjectMapper', '~> 5.0'
#pod 'DTTextField'
pod 'MBProgressHUD', '~> 1.1.0'
pod 'FacebookCore'
pod 'FacebookLogin'
pod 'FacebookShare'
pod 'ESTabBarController-swift'
pod 'ScrollableSegmentedControl'
pod 'DTGradientButton'
pod 'SwiftMoment'
pod 'SwiftyJSON', '~> 4.0'
pod 'Alamofire-SwiftyJSON'
pod 'STPopup'
#pod 'YKPhotoCircleCrop'
pod 'DKImagePickerController'
pod 'RichEditorView'
#pod 'BMPlayer', '~> 1.0.0'
#pod 'BMPlayer/CacheSupport', :git => 'https://github.com/BrikerMan/BMPlayer.git'
pod 'NVActivityIndicatorView'
pod 'SnapKit'
pod 'VIMediaCache'
pod 'Reveal-SDK', :configurations => ['Debug']
pod 'SwipeBack'

# Chatto
#pod 'Chatto'
#pod 'ChattoAdditions'
pod 'Socket.IO-Client-Swift'
pod 'JSQMessagesViewController'
pod 'SVPullToRefresh'

pod 'PixelEngine'
pod 'PixelEditor'

end
