source 'https://github.com/CocoaPods/Specs.git'
platform :ios, '10.0'
use_frameworks!

target 'FeedTrue' do
pod 'Alamofire', '~> 4.7'
pod 'AlamofireObjectMapper', '~> 5.0'
pod 'DTTextField'
pod 'MBProgressHUD', '~> 1.1.0'
pod 'FacebookCore'
pod 'FacebookLogin'
pod 'FacebookShare'
pod 'ESTabBarController-swift'
pod 'ScrollableSegmentedControl', '~> 1.3.0'
pod 'DTGradientButton'
end
